# Generated by Django 5.0.1 on 2025-10-22 08:14

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='사용자명')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('password_hash', models.CharField(db_column='password_hash', max_length=255, verbose_name='비밀번호')),
                ('role', models.CharField(choices=[('user', '일반 사용자'), ('dept_admin', '부서 관리자'), ('super_admin', '슈퍼 관리자')], default='user', max_length=20, verbose_name='역할')),
                ('status', models.CharField(choices=[('active', '활성'), ('pending', '승인 대기'), ('suspended', '정지')], default='pending', max_length=20, verbose_name='상태')),
                ('first_name', models.CharField(blank=True, default='', max_length=150, verbose_name='이름')),
                ('last_name', models.CharField(blank=True, default='', max_length=150, verbose_name='성')),
                ('is_staff', models.BooleanField(default=False, verbose_name='스태프 권한')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='슈퍼유저 권한')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='마지막 로그인')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='가입일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자 목록',
                'db_table': 'user',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='요청일')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='처리일')),
                ('status', models.CharField(choices=[('pending', '대기 중'), ('approved', '승인됨'), ('rejected', '거부됨')], default='pending', max_length=20, verbose_name='상태')),
                ('note', models.TextField(blank=True, default='', verbose_name='비고')),
            ],
            options={
                'verbose_name': '관리자 권한 요청',
                'verbose_name_plural': '관리자 권한 요청 목록',
                'db_table': 'admin_request',
                'ordering': ['-requested_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='회사명')),
                ('domain', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='도메인')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '회사',
                'verbose_name_plural': '회사 목록',
                'db_table': 'company',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='부서명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '부서',
                'verbose_name_plural': '부서 목록',
                'db_table': 'department',
                'ordering': ['company', 'name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('reset_id', models.AutoField(primary_key=True, serialize=False)),
                ('temp_password', models.CharField(max_length=255, verbose_name='임시 비밀번호')),
                ('expires_at', models.DateTimeField(verbose_name='만료일')),
                ('status', models.CharField(choices=[('pending', '대기 중'), ('completed', '완료됨'), ('expired', '만료됨')], default='pending', max_length=20, verbose_name='상태')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='요청일')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='처리일')),
            ],
            options={
                'verbose_name': '비밀번호 초기화 요청',
                'verbose_name_plural': '비밀번호 초기화 요청 목록',
                'db_table': 'password_reset_request',
                'ordering': ['-requested_at'],
                'managed': False,
            },
        ),
    ]
