# Generated by Django 5.0.1 on 2025-10-22 16:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.TextField(verbose_name='검색어')),
                ('search_type', models.CharField(choices=[('patent', '특허'), ('paper', '논문'), ('reject', '거절결정'), ('law', '특허법'), ('integrated', '통합검색')], max_length=50, verbose_name='검색 유형')),
                ('results_count', models.IntegerField(default=0, verbose_name='결과 개수')),
                ('results_summary', models.JSONField(blank=True, null=True, verbose_name='결과 요약')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('is_shared', models.BooleanField(default=True, help_text='True면 같은 부서 전체 공유', verbose_name='부서 공유')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='회사')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.department', verbose_name='부서')),
            ],
            options={
                'verbose_name': '검색 히스토리',
                'verbose_name_plural': '검색 히스토리 목록',
                'db_table': 'search_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'department', '-created_at'], name='search_hist_company_b08412_idx'), models.Index(fields=['created_by', '-created_at'], name='search_hist_created_617a0b_idx')],
            },
        ),
    ]
