# Generated by Django 5.0.1 on 2025-11-02 17:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='사용자명')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('password_hash', models.CharField(db_column='password_hash', max_length=255, verbose_name='비밀번호')),
                ('role', models.CharField(choices=[('user', '일반 사용자'), ('dept_admin', '부서 관리자'), ('super_admin', '슈퍼 관리자')], default='user', max_length=20, verbose_name='역할')),
                ('status', models.CharField(choices=[('active', '활성'), ('pending', '승인 대기'), ('suspended', '정지')], default='pending', max_length=20, verbose_name='상태')),
                ('first_name', models.CharField(blank=True, default='', max_length=150, verbose_name='이름')),
                ('last_name', models.CharField(blank=True, default='', max_length=150, verbose_name='성')),
                ('is_staff', models.BooleanField(default=False, help_text='role에서 자동 동기화', verbose_name='스태프 권한')),
                ('is_active', models.BooleanField(default=True, help_text='status에서 자동 동기화', verbose_name='활성 상태')),
                ('is_superuser', models.BooleanField(default=False, help_text='role에서 자동 동기화', verbose_name='슈퍼유저 권한')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='마지막 로그인')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='가입일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자 목록',
                'db_table': 'user',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('user_approval', '회원 승인 요청'), ('dept_admin', '부서 관리자 권한 요청'), ('password_reset', '비밀번호 초기화 요청')], default='user_approval', max_length=20, verbose_name='요청 타입')),
                ('status', models.CharField(choices=[('pending', '대기 중'), ('approved', '승인됨'), ('rejected', '거부됨')], default='pending', max_length=20, verbose_name='상태')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='요청일')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='처리일')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='비고')),
            ],
            options={
                'verbose_name': '관리 요청',
                'verbose_name_plural': '관리 요청 목록',
                'db_table': 'admin_request',
                'ordering': ['-requested_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='회사명')),
                ('domain', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='도메인')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '회사',
                'verbose_name_plural': '회사 목록',
                'db_table': 'company',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='부서명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '부서',
                'verbose_name_plural': '부서 목록',
                'db_table': 'department',
                'ordering': ['company', 'name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.TextField(verbose_name='검색어')),
                ('search_type', models.CharField(choices=[('patent', '특허'), ('paper', '논문'), ('reject', '거절결정'), ('law', '특허법'), ('integrated', '통합검색')], max_length=50, verbose_name='검색 유형')),
                ('results_count', models.IntegerField(default=0, verbose_name='결과 개수')),
                ('results_summary', models.JSONField(blank=True, null=True, verbose_name='결과 요약')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('is_shared', models.BooleanField(default=True, help_text='True면 같은 부서 전체 공유', verbose_name='부서 공유')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='회사')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.department', verbose_name='부서')),
            ],
            options={
                'verbose_name': '검색 히스토리',
                'verbose_name_plural': '검색 히스토리 목록',
                'db_table': 'search_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'department', '-created_at'], name='search_hist_company_b08412_idx'), models.Index(fields=['created_by', '-created_at'], name='search_hist_created_617a0b_idx')],
            },
        ),
    ]
