#!/bin/bash

echo "============================================================"
echo "  OpenSearch papers 인덱스 확인 명령어"
echo "============================================================"
echo ""
echo "EC2 서버에서 다음 명령어들을 실행하세요:"
echo ""
echo "1. OpenSearch 터널 설정 (먼저 실행):"
echo "   ./start_opensearch_tunnel.sh"
echo ""
echo "2. papers 인덱스 존재 확인:"
echo "   curl -X GET 'https://localhost:9200/papers/_count?pretty' -u 'opensearch_admin:3-Bengio123' -k"
echo ""
echo "3. papers 인덱스 매핑 확인 (필드 목록):"
echo "   curl -X GET 'https://localhost:9200/papers/_mapping?pretty' -u 'opensearch_admin:3-Bengio123' -k | grep -A 1 '\"type\"'"
echo ""
echo "4. 샘플 문서 확인:"
echo "   curl -X GET 'https://localhost:9200/papers/_search?pretty&size=1' -u 'opensearch_admin:3-Bengio123' -k"
echo ""
echo "5. published_date 필드가 있는 문서 수:"
echo "   curl -X GET 'https://localhost:9200/papers/_count?pretty' -u 'opensearch_admin:3-Bengio123' -k -H 'Content-Type: application/json' -d '{\"query\":{\"exists\":{\"field\":\"published_date\"}}}'"
echo ""
echo "============================================================"
echo ""
echo "또는 Python 스크립트로 확인:"
echo ""
echo "   cd /home/ubuntu/SKN15-FINAL-3TEAM/patent_backend"
echo "   DJANGO_SETTINGS_MODULE=config.settings python3 check_opensearch_papers.py"
echo ""
echo "============================================================"
