# Generated by Django 5.0.1 on 2025-11-04 03:52

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.TextField(blank=True, null=True, verbose_name='제목(영문)')),
                ('title_kr', models.TextField(db_index=True, verbose_name='제목(한글)')),
                ('authors', models.TextField(blank=True, null=True, verbose_name='저자')),
                ('abstract_en', models.TextField(blank=True, null=True, verbose_name='초록(영문)')),
                ('abstract_kr', models.TextField(blank=True, null=True, verbose_name='초록(한글)')),
                ('abstract_page_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='논문 페이지 링크')),
                ('pdf_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='PDF 링크')),
                ('source_file', models.CharField(blank=True, max_length=255, null=True, verbose_name='출처 파일')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='데이터 생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='데이터 수정일')),
            ],
            options={
                'verbose_name': '논문',
                'verbose_name_plural': '논문 목록',
                'db_table': 'papers',
                'ordering': ['-created_at'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='papers_search__f7a0dd_gin')],
            },
        ),
    ]
