# Generated by Django 5.2.7 on 2025-11-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='published_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='발행일'),
        ),
    ]
