# Generated by Django 5.0.1 on 2025-11-02 16:56

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500, verbose_name='발명의명칭')),
                ('title_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='발명의명칭(영문)')),
                ('application_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='출원번호')),
                ('application_date', models.CharField(blank=True, max_length=20, null=True, verbose_name='출원일자')),
                ('applicant', models.TextField(blank=True, null=True, verbose_name='출원인')),
                ('registration_number', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='등록번호')),
                ('registration_date', models.CharField(blank=True, max_length=20, null=True, verbose_name='등록일자')),
                ('ipc_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='IPC분류')),
                ('cpc_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='CPC분류')),
                ('abstract', models.TextField(blank=True, null=True, verbose_name='요약')),
                ('claims', models.TextField(blank=True, null=True, verbose_name='청구항')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='데이터 생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='데이터 수정일')),
            ],
            options={
                'verbose_name': '특허',
                'verbose_name_plural': '특허 목록',
                'db_table': 'patents',
                'ordering': ['-application_date'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='patents_search__dd76db_gin'), models.Index(fields=['application_date'], name='patents_applica_5526f1_idx'), models.Index(fields=['registration_date'], name='patents_registr_67d717_idx')],
            },
        ),
    ]
