# Generated by Django 5.0.1 on 2025-11-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='cpc_code',
            field=models.TextField(blank=True, null=True, verbose_name='CPC분류'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='ipc_code',
            field=models.TextField(blank=True, null=True, verbose_name='IPC분류'),
        ),
    ]
