# Generated by Django 5.0.1 on 2025-11-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0002_alter_patent_cpc_code_alter_patent_ipc_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='문서ID')),
                ('send_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='발송번호')),
                ('send_date', models.CharField(blank=True, max_length=20, null=True, verbose_name='발송일자')),
                ('applicant_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='출원인코드')),
                ('applicant', models.TextField(blank=True, null=True, verbose_name='출원인')),
                ('agent', models.TextField(blank=True, null=True, verbose_name='대리인')),
                ('application_number', models.CharField(db_index=True, max_length=50, verbose_name='출원번호')),
                ('invention_name', models.TextField(blank=True, null=True, verbose_name='발명의_명칭')),
                ('examination_office', models.TextField(blank=True, null=True, verbose_name='심사기관')),
                ('examiner', models.CharField(blank=True, max_length=100, null=True, verbose_name='심사관')),
                ('tables_raw', models.TextField(blank=True, null=True, verbose_name='표_원본')),
                ('processed_text', models.TextField(blank=True, null=True, verbose_name='거절사유_내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='데이터 생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='데이터 수정일')),
            ],
            options={
                'verbose_name': '거절 사유 문서',
                'verbose_name_plural': '거절 사유 문서 목록',
                'db_table': 'reject_documents',
                'ordering': ['-send_date'],
                'indexes': [models.Index(fields=['application_number'], name='reject_docu_applica_52aa79_idx'), models.Index(fields=['send_date'], name='reject_docu_send_da_ea8ad9_idx')],
            },
        ),
    ]
