# Generated by Django 5.0.1 on 2025-11-18 00:59

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0005_patent_legal_status'),
    ]

    operations = [
        # pgvector 확장은 수동으로 설치 필요:
        # psql -U postgres -d patentdb -c "CREATE EXTENSION IF NOT EXISTS vector;"
        migrations.CreateModel(
            name='PatentRAGDocument',
            fields=[
                ('doc_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='문서ID')),
                ('application_number', models.CharField(db_index=True, max_length=50, verbose_name='출원번호')),
                ('title_ko', models.TextField(blank=True, null=True, verbose_name='발명의 명칭(한글)')),
                ('title_en', models.TextField(blank=True, null=True, verbose_name='발명의 명칭(영문)')),
                ('ipc', models.TextField(blank=True, null=True, verbose_name='IPC 분류')),
                ('text', models.TextField(verbose_name='특허 전문 텍스트')),
                ('source_ids', models.CharField(blank=True, max_length=255, null=True, verbose_name='출처 파일')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024, verbose_name='임베딩 벡터')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='데이터 생성일')),
            ],
            options={
                'verbose_name': 'RAG 특허 문서',
                'verbose_name_plural': 'RAG 특허 문서 목록',
                'db_table': 'patent_rag_documents',
            },
        ),
        migrations.RenameIndex(
            model_name='opiniondocument',
            new_name='opinion_doc_applica_a8bd3e_idx',
            old_name='opinion_doc_applica_idx',
        ),
        migrations.AddIndex(
            model_name='patentragdocument',
            index=models.Index(fields=['application_number'], name='patent_rag__applica_1c8d72_idx'),
        ),
    ]
